### ISSUE TITLE
Why is it so terribly complicated to install?

### ISSUE THREAD

**Issue by xaiamov** [sandoche/Mobile-app-landingpage-template#10]
The template is simple and that is why I was intended to use it. But having to compile and build something with installing additional libs to the system prevent me doing that.

I have such a big number of errors after npm install that I confuse to paste them all. How could you make such simple things so hard to use??! I am unable to implement it in my project :(

These are just a small part:

$ npm install

> fsevents@1.2.4 install /Users/denis/www/iwonder/ru/simple/node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v83-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@14.15.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
.....
../../nan/nan_converters_43_inl.h:22:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(Boolean)
^~~~~~~~~~
../../nan/nan_converters_43_inl.h:18:23: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/denis/Library/Caches/node-gyp/14.15.0/include/node/v8.h:2848:37: note: passing argument to parameter 'isolate' here
  Local<Boolean> ToBoolean(Isolate* isolate) const;
                                    ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:40:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(bool, Boolean)
^~~~~~~~~~~~~~~~

...

In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:58: error: expected '(' for function-style cast or type construction
  return v8::StringObject::New(value).As<v8::StringObject>();
                                         ~~~~~~~~~~~~~~~~^

**Comment by sandoche** [comment]
The problem may be due because of the node version you are using.
You need node 8.17.0

Another alternative no-code is to use this without coding:
https://t3mpl.n4no.com/editor/#manifest=../templates/mobile-app-landing-page/template.yaml

**Comment by xaiamov** [comment]
Thank you for the answer. I guess the alternative variant is mine :)
